
package com.edicom.ediwinws.service.cfdi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CFDiService", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", wsdlLocation = "https://cfdiws.sedeb2b.com/EdiwinWS/services/CFDi?wsdl")
public class CFDiService
    extends Service
{

    private final static URL CFDISERVICE_WSDL_LOCATION;
    private final static WebServiceException CFDISERVICE_EXCEPTION;
    private final static QName CFDISERVICE_QNAME = new QName("http://cfdi.service.ediwinws.edicom.com", "CFDiService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://cfdiws.sedeb2b.com/EdiwinWS/services/CFDi?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CFDISERVICE_WSDL_LOCATION = url;
        CFDISERVICE_EXCEPTION = e;
    }

    public CFDiService() {
        super(__getWsdlLocation(), CFDISERVICE_QNAME);
    }

    public CFDiService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CFDISERVICE_QNAME, features);
    }

    public CFDiService(URL wsdlLocation) {
        super(wsdlLocation, CFDISERVICE_QNAME);
    }

    public CFDiService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CFDISERVICE_QNAME, features);
    }

    public CFDiService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CFDiService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CFDi
     */
    @WebEndpoint(name = "CFDi")
    public CFDi getCFDi() {
        return super.getPort(new QName("http://cfdi.service.ediwinws.edicom.com", "CFDi"), CFDi.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CFDi
     */
    @WebEndpoint(name = "CFDi")
    public CFDi getCFDi(WebServiceFeature... features) {
        return super.getPort(new QName("http://cfdi.service.ediwinws.edicom.com", "CFDi"), CFDi.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CFDISERVICE_EXCEPTION!= null) {
            throw CFDISERVICE_EXCEPTION;
        }
        return CFDISERVICE_WSDL_LOCATION;
    }

}
