
package com.edicom.ediwinws.service.cfdi;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CFDi", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CFDi {


    /**
     * 
     * @param password
     * @param file
     * @param user
     * @return
     *     returns byte[]
     * @throws CFDiException_Exception
     */
    @WebMethod
    @WebResult(name = "getTimbreCfdiReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "getTimbreCfdi", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.GetTimbreCfdi")
    @ResponseWrapper(localName = "getTimbreCfdiResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.GetTimbreCfdiResponse")
    public byte[] getTimbreCfdi(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file)
        throws CFDiException_Exception
    ;

    /**
     * 
     * @param password
     * @param file
     * @param user
     * @return
     *     returns byte[]
     * @throws CFDiException_Exception
     */
    @WebMethod
    @WebResult(name = "getTimbreCfdiTestReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "getTimbreCfdiTest", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.GetTimbreCfdiTest")
    @ResponseWrapper(localName = "getTimbreCfdiTestResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.GetTimbreCfdiTestResponse")
    public byte[] getTimbreCfdiTest(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file)
        throws CFDiException_Exception
    ;

    /**
     * 
     * @param password
     * @param file
     * @param user
     * @return
     *     returns byte[]
     * @throws CFDiException_Exception
     */
    @WebMethod
    @WebResult(name = "getCfdiTestReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "getCfdiTest", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.GetCfdiTest")
    @ResponseWrapper(localName = "getCfdiTestResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.GetCfdiTestResponse")
    public byte[] getCfdiTest(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file)
        throws CFDiException_Exception
    ;

    /**
     * 
     * @param password
     * @param test
     * @param sign
     * @param user
     * @return
     *     returns com.edicom.ediwinws.service.cfdi.CancelaResponse
     * @throws CFDiException_Exception
     */
    @WebMethod
    @WebResult(name = "cancelaCFDiRetencionesSignedReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "cancelaCFDiRetencionesSigned", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.CancelaCFDiRetencionesSigned")
    @ResponseWrapper(localName = "cancelaCFDiRetencionesSignedResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.CancelaCFDiRetencionesSignedResponse")
    public CancelaResponse cancelaCFDiRetencionesSigned(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String password,
        @WebParam(name = "sign", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] sign,
        @WebParam(name = "test", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        boolean test)
        throws CFDiException_Exception
    ;

    /**
     * 
     * @param password
     * @param file
     * @param user
     * @return
     *     returns byte[]
     * @throws CFDiException_Exception
     */
    @WebMethod
    @WebResult(name = "getCfdiRetencionesTestReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "getCfdiRetencionesTest", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.GetCfdiRetencionesTest")
    @ResponseWrapper(localName = "getCfdiRetencionesTestResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.GetCfdiRetencionesTestResponse")
    public byte[] getCfdiRetencionesTest(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file)
        throws CFDiException_Exception
    ;

    /**
     * 
     * @param password
     * @param file
     * @param user
     * @return
     *     returns byte[]
     * @throws CFDiException_Exception
     */
    @WebMethod
    @WebResult(name = "getTimbreCfdiRetencionesReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "getTimbreCfdiRetenciones", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.GetTimbreCfdiRetenciones")
    @ResponseWrapper(localName = "getTimbreCfdiRetencionesResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.GetTimbreCfdiRetencionesResponse")
    public byte[] getTimbreCfdiRetenciones(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file)
        throws CFDiException_Exception
    ;

    /**
     * 
     * @param password
     * @param file
     * @param user
     * @return
     *     returns byte[]
     * @throws CFDiException_Exception
     */
    @WebMethod
    @WebResult(name = "getTimbreCfdiRetencionesTestReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "getTimbreCfdiRetencionesTest", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.GetTimbreCfdiRetencionesTest")
    @ResponseWrapper(localName = "getTimbreCfdiRetencionesTestResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.GetTimbreCfdiRetencionesTestResponse")
    public byte[] getTimbreCfdiRetencionesTest(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file)
        throws CFDiException_Exception
    ;

    /**
     * 
     * @param password
     * @param motivo
     * @param pfx
     * @param pfxPassword
     * @param test
     * @param user
     * @param uuid
     * @param rfc
     * @param sustitucion
     * @return
     *     returns com.edicom.ediwinws.service.cfdi.CancelaResponse
     * @throws CFDiException_Exception
     */
    @WebMethod
    @WebResult(name = "cancelaCFDiRetencionesReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "cancelaCFDiRetenciones", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.CancelaCFDiRetenciones")
    @ResponseWrapper(localName = "cancelaCFDiRetencionesResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.CancelaCFDiRetencionesResponse")
    public CancelaResponse cancelaCFDiRetenciones(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String password,
        @WebParam(name = "rfc", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String rfc,
        @WebParam(name = "uuid", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        List<String> uuid,
        @WebParam(name = "pfx", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] pfx,
        @WebParam(name = "pfxPassword", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String pfxPassword,
        @WebParam(name = "motivo", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String motivo,
        @WebParam(name = "sustitucion", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String sustitucion,
        @WebParam(name = "test", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        boolean test)
        throws CFDiException_Exception
    ;

    /**
     * 
     * @param password
     * @param file
     * @param user
     * @return
     *     returns java.lang.String
     * @throws CFDiException_Exception
     */
    @WebMethod
    @WebResult(name = "getUUIDTestReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "getUUIDTest", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.GetUUIDTest")
    @ResponseWrapper(localName = "getUUIDTestResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.GetUUIDTestResponse")
    public String getUUIDTest(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file)
        throws CFDiException_Exception
    ;

    /**
     * 
     * @param password
     * @param user
     * @param uuid
     * @param rfc
     * @return
     *     returns byte[]
     * @throws CFDiException_Exception
     */
    @WebMethod
    @WebResult(name = "getCfdiFromUUIDReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "getCfdiFromUUID", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.GetCfdiFromUUID")
    @ResponseWrapper(localName = "getCfdiFromUUIDResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.GetCfdiFromUUIDResponse")
    public byte[] getCfdiFromUUID(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String password,
        @WebParam(name = "rfc", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String rfc,
        @WebParam(name = "uuid", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        List<String> uuid)
        throws CFDiException_Exception
    ;

    /**
     * 
     * @param password
     * @param user
     * @param uuid
     * @return
     *     returns byte[]
     * @throws CFDiException_Exception
     */
    @WebMethod
    @WebResult(name = "getCfdiAckReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "getCfdiAck", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.GetCfdiAck")
    @ResponseWrapper(localName = "getCfdiAckResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.GetCfdiAckResponse")
    public byte[] getCfdiAck(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String password,
        @WebParam(name = "uuid", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        List<String> uuid)
        throws CFDiException_Exception
    ;

    /**
     * 
     * @param password
     * @param file
     * @param user
     * @return
     *     returns byte[]
     * @throws CFDiException_Exception
     */
    @WebMethod
    @WebResult(name = "getCfdiExtReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "getCfdiExt", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.GetCfdiExt")
    @ResponseWrapper(localName = "getCfdiExtResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.GetCfdiExtResponse")
    public byte[] getCfdiExt(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file)
        throws CFDiException_Exception
    ;

    /**
     * 
     * @param password
     * @param file
     * @param user
     * @return
     *     returns byte[]
     * @throws CFDiException_Exception
     */
    @WebMethod
    @WebResult(name = "getCfdiExtTestReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "getCfdiExtTest", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.GetCfdiExtTest")
    @ResponseWrapper(localName = "getCfdiExtTestResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.GetCfdiExtTestResponse")
    public byte[] getCfdiExtTest(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file)
        throws CFDiException_Exception
    ;

    /**
     * 
     * @param password
     * @param endDate
     * @param iniDate
     * @param user
     * @param rfc
     * @return
     *     returns byte[]
     * @throws CFDiException_Exception
     */
    @WebMethod
    @WebResult(name = "exportCfdiReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "exportCfdi", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.ExportCfdi")
    @ResponseWrapper(localName = "exportCfdiResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.ExportCfdiResponse")
    public byte[] exportCfdi(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String password,
        @WebParam(name = "rfc", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String rfc,
        @WebParam(name = "iniDate", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        XMLGregorianCalendar iniDate,
        @WebParam(name = "endDate", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        XMLGregorianCalendar endDate)
        throws CFDiException_Exception
    ;

    /**
     * 
     * @param password
     * @param total
     * @param rfcE
     * @param test
     * @param rfcR
     * @param user
     * @param uuid
     * @return
     *     returns com.edicom.ediwinws.service.cfdi.CancelQueryData
     * @throws CFDiException_Exception
     */
    @WebMethod
    @WebResult(name = "getCFDiStatusReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "getCFDiStatus", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.GetCFDiStatus")
    @ResponseWrapper(localName = "getCFDiStatusResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.GetCFDiStatusResponse")
    public CancelQueryData getCFDiStatus(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String password,
        @WebParam(name = "rfcE", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String rfcE,
        @WebParam(name = "rfcR", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String rfcR,
        @WebParam(name = "uuid", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String uuid,
        @WebParam(name = "total", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        double total,
        @WebParam(name = "test", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        boolean test)
        throws CFDiException_Exception
    ;

    /**
     * 
     * @param password
     * @param motivo
     * @param pfx
     * @param pfxPassword
     * @param user
     * @param uuid
     * @param rfc
     * @param sustitucion
     * @return
     *     returns com.edicom.ediwinws.service.cfdi.CancelaResponse
     * @throws CFDiException_Exception
     */
    @WebMethod
    @WebResult(name = "cancelaCFDiReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "cancelaCFDi", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.CancelaCFDi")
    @ResponseWrapper(localName = "cancelaCFDiResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.CancelaCFDiResponse")
    public CancelaResponse cancelaCFDi(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String password,
        @WebParam(name = "rfc", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String rfc,
        @WebParam(name = "uuid", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        List<String> uuid,
        @WebParam(name = "pfx", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] pfx,
        @WebParam(name = "pfxPassword", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String pfxPassword,
        @WebParam(name = "motivo", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String motivo,
        @WebParam(name = "sustitucion", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String sustitucion)
        throws CFDiException_Exception
    ;

    /**
     * 
     * @param password
     * @param sign
     * @param user
     * @return
     *     returns com.edicom.ediwinws.service.cfdi.CancelaResponse
     * @throws CFDiException_Exception
     */
    @WebMethod
    @WebResult(name = "cancelaCFDiSignedReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "cancelaCFDiSigned", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.CancelaCFDiSigned")
    @ResponseWrapper(localName = "cancelaCFDiSignedResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.CancelaCFDiSignedResponse")
    public CancelaResponse cancelaCFDiSigned(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String password,
        @WebParam(name = "sign", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] sign)
        throws CFDiException_Exception
    ;

    /**
     * 
     * @param password
     * @param total
     * @param motivo
     * @param rfcE
     * @param pfx
     * @param pfxPassword
     * @param test
     * @param rfcR
     * @param user
     * @param uuid
     * @param sustitucion
     * @return
     *     returns com.edicom.ediwinws.service.cfdi.CancelData
     * @throws CFDiException_Exception
     */
    @WebMethod
    @WebResult(name = "cancelCFDiAsyncReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "cancelCFDiAsync", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.CancelCFDiAsync")
    @ResponseWrapper(localName = "cancelCFDiAsyncResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.CancelCFDiAsyncResponse")
    public CancelData cancelCFDiAsync(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String password,
        @WebParam(name = "rfcE", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String rfcE,
        @WebParam(name = "rfcR", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String rfcR,
        @WebParam(name = "uuid", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String uuid,
        @WebParam(name = "total", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        double total,
        @WebParam(name = "pfx", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] pfx,
        @WebParam(name = "pfxPassword", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String pfxPassword,
        @WebParam(name = "motivo", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String motivo,
        @WebParam(name = "sustitucion", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String sustitucion,
        @WebParam(name = "test", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        boolean test)
        throws CFDiException_Exception
    ;

    /**
     * 
     * @param password
     * @param total
     * @param rfcE
     * @param test
     * @param rfcR
     * @param sign
     * @param user
     * @param uuid
     * @return
     *     returns com.edicom.ediwinws.service.cfdi.CancelData
     * @throws CFDiException_Exception
     */
    @WebMethod
    @WebResult(name = "cancelCFDiSignedAsyncReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "cancelCFDiSignedAsync", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.CancelCFDiSignedAsync")
    @ResponseWrapper(localName = "cancelCFDiSignedAsyncResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.CancelCFDiSignedAsyncResponse")
    public CancelData cancelCFDiSignedAsync(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String password,
        @WebParam(name = "sign", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] sign,
        @WebParam(name = "rfcE", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String rfcE,
        @WebParam(name = "rfcR", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String rfcR,
        @WebParam(name = "uuid", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String uuid,
        @WebParam(name = "total", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        double total,
        @WebParam(name = "test", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        boolean test)
        throws CFDiException_Exception
    ;

    /**
     * 
     * @param password
     * @param file
     * @param user
     * @return
     *     returns byte[]
     * @throws CFDiException_Exception
     */
    @WebMethod
    @WebResult(name = "getCfdiRetencionesReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "getCfdiRetenciones", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.GetCfdiRetenciones")
    @ResponseWrapper(localName = "getCfdiRetencionesResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.GetCfdiRetencionesResponse")
    public byte[] getCfdiRetenciones(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file)
        throws CFDiException_Exception
    ;

    /**
     * 
     * @param password
     * @param file
     * @param user
     * @return
     *     returns byte[]
     * @throws CFDiException_Exception
     */
    @WebMethod
    @WebResult(name = "getCfdiReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "getCfdi", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.GetCfdi")
    @ResponseWrapper(localName = "getCfdiResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.GetCfdiResponse")
    public byte[] getCfdi(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file)
        throws CFDiException_Exception
    ;

    /**
     * 
     * @param password
     * @param file
     * @param user
     * @return
     *     returns java.lang.String
     * @throws CFDiException_Exception
     */
    @WebMethod
    @WebResult(name = "getUUIDReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "getUUID", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.GetUUID")
    @ResponseWrapper(localName = "getUUIDResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.GetUUIDResponse")
    public String getUUID(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String password,
        @WebParam(name = "file", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        byte[] file)
        throws CFDiException_Exception
    ;

    /**
     * 
     * @param password
     * @param newPassword
     * @param user
     * @return
     *     returns boolean
     * @throws CFDiException_Exception
     */
    @WebMethod
    @WebResult(name = "changePasswordReturn", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
    @RequestWrapper(localName = "changePassword", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.ChangePassword")
    @ResponseWrapper(localName = "changePasswordResponse", targetNamespace = "http://cfdi.service.ediwinws.edicom.com", className = "com.edicom.ediwinws.service.cfdi.ChangePasswordResponse")
    public boolean changePassword(
        @WebParam(name = "user", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String user,
        @WebParam(name = "password", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String password,
        @WebParam(name = "newPassword", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
        String newPassword)
        throws CFDiException_Exception
    ;

}
