
package com.edicom.ediwinws.service.cfdi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "fault", targetNamespace = "http://cfdi.service.ediwinws.edicom.com")
public class CFDiException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private CFDiException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public CFDiException_Exception(String message, CFDiException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public CFDiException_Exception(String message, CFDiException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.edicom.ediwinws.service.cfdi.CFDiException
     */
    public CFDiException getFaultInfo() {
        return faultInfo;
    }

}
